namespace UnityClientServerModel;
public enum Tags
{
    None = 0,
    DEBUG_SEND_TO_CLIENT_REQUEST = 100,
    DEBUG_SEND_TO_CLIENT_RESULT,
    DEBUG_SEND_TO_SERVER_REQUEST,
    DEBUG_SEND_TO_SERVER_RESULT,
    
    // patching
    CHECK_VERSION_REQUEST = 900,
    CHECK_VERSION_SUCCESS,
    CHECK_VERSION_FAILED,
    UPDATE_VERSION_REQUEST,
    UPDATE_VERSION_SUCCESS,
    UPDATE_VERSION_FAILED,
    GET_SERVER_LIST_REQUEST,
    GET_SERVER_LIST_SUCCESS,
    GET_SERVER_LIST_FAILED,
    // Logic - Login
    SIGN_UP_REQUEST = 1000,
    SIGN_UP_SUCCESS,
    SIGN_UP_FAILED,
    SIGN_IN_REQUEST,
    SIGN_IN_SUCCESS,
    SIGN_IN_FAILED,
    SIGN_OUT_REQUEST,
    SIGN_OUT_SUCCESS,
    SIGN_OUT_FAILED,
    // Create - Character
    CREATE_CHARACTER_REQUEST = 1100,
    CREATE_CHARACTER_SUCCESS,
    CREATE_CHARACTER_FAILED,
    REMOVE_CHARACTER_REQUEST,
    REMOVE_CHARACTER_SUCCESS,
    REMOVE_CHARACTER_FAILED,
    ENTER_WORLD_REQUEST,
    ENTER_WORLD_SUCCESS,
    ENTER_WORLD_FAILED,
}